# To create, use mamba (or conda):
# mamba env create -f environment.yml
# To recreate from scratch, remove previously created environment first:
# mamba remove -n d25a-rsl-fusion --all
name: d25a-rsl-fusion
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - xarray
  - NetCDF4
  - scipy
  - matplotlib
  - seaborn
  - cartopy
  - watermark
